
server:
  port: 7001
spring:
  application:
    name: cloud-config
  cloud:
    config:
      label: master  # git仓库分支
      server:
        git:
          uri: https://github.com/liyahui888/config-repo.git
          username: 648267806@qq.com
          password: lyh135212
          search-paths: config-repo  　  #这里可以写死，也可以写成{profile}来动态化
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@server1:8761/eureka/,http://admin:123456@server2:8762/eureka/     #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心


