server:
  port: 6001

#服务的名称
spring:
  application:
    name: cloud-zuul

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@server1:8761/eureka/,http://admin:123456@server2:8762/eureka/


