server:
    port: 8088
spring:
  application:
           name: cloud-provider
  datasource:
           username: root
           password: root
           url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
           driver-class-name: com.mysql.jdbc.Driver
           hikari:
             minimum-idle: 5
             maximum-pool-size: 15
             auto-commit: true
             idle-timeout: 30000
             pool-name: HikariCP
             max-lifetime: 1800000
             connection-timeout: 30000
             connection-test-query: SELECT 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@server1:8761/eureka/,http://admin:123456@server2:8762/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心

#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.cloud.provider.entity